Repository Consensys/web3signer, pull requests merged in 2020-09, with the labels that each got.

#202 Create signing submodes
  acceptance-tests/src/gatling/simulations/FcBlsSignSimulation.scala
  acceptance-tests/src/test/java/tech/pegasys/web3signer/dsl/signer/SignerConfiguration.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/dsl/signer/SignerConfigurationBuilder.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/dsl/signer/runner/Web3SignerRunner.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/AcceptanceTestBase.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/HttpHostAllowListAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/MetricsAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/MetricsHostAllowListAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/SwaggerUIAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/UpcheckAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/comparison/CompareApisAcceptanceTestBase.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcBlsSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcBlsVerifyAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcSecpSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcSecpVerifyAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcSignMessageAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/publickeys/FilecoinKeyIdentifiersAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/publickeys/KeyIdentifiersAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/publickeys/KeyIdentifiersAcceptanceTestBase.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/BlsSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/KeyLoadAndSignAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/SecpSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/SigningAcceptanceTestBase.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/tls/ServerSideTlsAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/tls/ServerSideTlsCaClientAcceptanceTest.java
  app/src/main/java/tech/pegasys/web3signer/Web3SignerApp.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/CommandlineParser.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/Web3SignerCommand.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/subcommands/Eth1SubCommand.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/subcommands/Eth2SubCommand.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/subcommands/FilecoinSubCommand.java
  commandline/src/main/java/tech/pegasys/web3signer/commandline/subcommands/ModeSubCommand.java
  core/src/main/java/tech/pegasys/web3signer/core/Context.java
  core/src/main/java/tech/pegasys/web3signer/core/Eth1Runner.java
  core/src/main/java/tech/pegasys/web3signer/core/Eth2Runner.java
  core/src/main/java/tech/pegasys/web3signer/core/FilecoinRunner.java
  core/src/main/java/tech/pegasys/web3signer/core/Runner.java
  docker/test.sh
Labels: TeamGroot

#217 update user doc url
  README.md
Labels: documentation

#222 YubiHSM2 Integration
  acceptance-tests/src/test/java/tech/pegasys/web3signer/dsl/utils/MetadataFileHelpers.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/filecoin/FcBlsSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/BlsSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/SecpSigningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/web3signer/tests/signing/SigningAcceptanceTestBase.java
  acceptance-tests/src/test/resources/YubiShellSimulator.java
  core/build.gradle
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/AbstractArtifactSignerFactory.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/ArtifactSignerFactory.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/BlsArtifactSignerFactory.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/Secp256k1ArtifactSignerFactory.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/SigningMetadata.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/YubiHsm2SigningMetadata.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/YubiHsmShellArgs.java
  core/src/main/java/tech/pegasys/web3signer/core/multikey/metadata/parser/YamlSignerParser.java
  core/src/test/java/tech/pegasys/web3signer/core/multikey/metadata/YubiHsm2SigningMetadataParsingTest.java
  gradle/versions.gradle
Labels: TeamGroot, documentation
